/**
 * ProWritingAid API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApi) {
      root.ProWritingAidApi = {};
    }
    root.ProWritingAidApi.AnalysisSettings = factory(root.ProWritingAidApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AnalysisSettings model module.
   * @module model/AnalysisSettings
   * @version v1
   */

  /**
   * Constructs a new <code>AnalysisSettings</code>.
   * @alias module:model/AnalysisSettings
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>AnalysisSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalysisSettings} obj Optional instance to populate.
   * @return {module:model/AnalysisSettings} The populated <code>AnalysisSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ShortestAverageSentenceLength')) {
        obj['ShortestAverageSentenceLength'] = ApiClient.convertToType(data['ShortestAverageSentenceLength'], 'Integer');
      }
      if (data.hasOwnProperty('LongestAverageSentenceLength')) {
        obj['LongestAverageSentenceLength'] = ApiClient.convertToType(data['LongestAverageSentenceLength'], 'Integer');
      }
      if (data.hasOwnProperty('LongestIndividualSentence')) {
        obj['LongestIndividualSentence'] = ApiClient.convertToType(data['LongestIndividualSentence'], 'Integer');
      }
      if (data.hasOwnProperty('HighestPassiveIndex')) {
        obj['HighestPassiveIndex'] = ApiClient.convertToType(data['HighestPassiveIndex'], 'Integer');
      }
      if (data.hasOwnProperty('MaxGlueIndex')) {
        obj['MaxGlueIndex'] = ApiClient.convertToType(data['MaxGlueIndex'], 'Integer');
      }
      if (data.hasOwnProperty('MinSentenceVariety')) {
        obj['MinSentenceVariety'] = ApiClient.convertToType(data['MinSentenceVariety'], 'Integer');
      }
      if (data.hasOwnProperty('HighestPronounPercentage')) {
        obj['HighestPronounPercentage'] = ApiClient.convertToType(data['HighestPronounPercentage'], 'Number');
      }
      if (data.hasOwnProperty('LowestPronounPercentage')) {
        obj['LowestPronounPercentage'] = ApiClient.convertToType(data['LowestPronounPercentage'], 'Number');
      }
      if (data.hasOwnProperty('HighestAcademicPronounPercentage')) {
        obj['HighestAcademicPronounPercentage'] = ApiClient.convertToType(data['HighestAcademicPronounPercentage'], 'Number');
      }
      if (data.hasOwnProperty('HighestInitialPronounPercentage')) {
        obj['HighestInitialPronounPercentage'] = ApiClient.convertToType(data['HighestInitialPronounPercentage'], 'Number');
      }
      if (data.hasOwnProperty('LowestInitialPronounPercentage')) {
        obj['LowestInitialPronounPercentage'] = ApiClient.convertToType(data['LowestInitialPronounPercentage'], 'Number');
      }
      if (data.hasOwnProperty('LowestWeWeScore')) {
        obj['LowestWeWeScore'] = ApiClient.convertToType(data['LowestWeWeScore'], 'Number');
      }
      if (data.hasOwnProperty('LongestAverageParagraphLength')) {
        obj['LongestAverageParagraphLength'] = ApiClient.convertToType(data['LongestAverageParagraphLength'], 'Number');
      }
    }
    return obj;
  }

  /**
   * <remarks>Default is 11</remarks>
   * @member {Integer} ShortestAverageSentenceLength
   */
  exports.prototype['ShortestAverageSentenceLength'] = 11;
  /**
   * <remarks>Default is 18</remarks>
   * @member {Integer} LongestAverageSentenceLength
   */
  exports.prototype['LongestAverageSentenceLength'] = 18;
  /**
   * <remarks>Default is 30</remarks>
   * @member {Integer} LongestIndividualSentence
   */
  exports.prototype['LongestIndividualSentence'] = 30;
  /**
   * <remarks>Default is 25</remarks>
   * @member {Integer} HighestPassiveIndex
   */
  exports.prototype['HighestPassiveIndex'] = 25;
  /**
   * <remarks>Default is 40</remarks>
   * @member {Integer} MaxGlueIndex
   */
  exports.prototype['MaxGlueIndex'] = 40;
  /**
   * <remarks>Default is 3</remarks>
   * @member {Integer} MinSentenceVariety
   */
  exports.prototype['MinSentenceVariety'] = 3;
  /**
   * <remarks>Default is 15</remarks>
   * @member {Number} HighestPronounPercentage
   */
  exports.prototype['HighestPronounPercentage'] = 15;
  /**
   * <remarks>Default is 4</remarks>
   * @member {Number} LowestPronounPercentage
   */
  exports.prototype['LowestPronounPercentage'] = 4;
  /**
   * <remarks>Default is 2</remarks>
   * @member {Number} HighestAcademicPronounPercentage
   */
  exports.prototype['HighestAcademicPronounPercentage'] = 2;
  /**
   * <remarks>Default is 30</remarks>
   * @member {Number} HighestInitialPronounPercentage
   */
  exports.prototype['HighestInitialPronounPercentage'] = 30;
  /**
   * <remarks>Default is 0</remarks>
   * @member {Number} LowestInitialPronounPercentage
   */
  exports.prototype['LowestInitialPronounPercentage'] = 0;
  /**
   * <remarks>Default is .6</remarks>
   * @member {Number} LowestWeWeScore
   */
  exports.prototype['LowestWeWeScore'] = 0.6;
  /**
   * <remarks>Default is 6</remarks>
   * @member {Number} LongestAverageParagraphLength
   */
  exports.prototype['LongestAverageParagraphLength'] = 6;



  return exports;
}));


