/**
 * ProWritingAid API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HtmlAnalysisResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HtmlAnalysisResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApi) {
      root.ProWritingAidApi = {};
    }
    root.ProWritingAidApi.AsyncResponseHtmlAnalysisResponse = factory(root.ProWritingAidApi.ApiClient, root.ProWritingAidApi.HtmlAnalysisResponse);
  }
}(this, function(ApiClient, HtmlAnalysisResponse) {
  'use strict';




  /**
   * The AsyncResponseHtmlAnalysisResponse model module.
   * @module model/AsyncResponseHtmlAnalysisResponse
   * @version v1
   */

  /**
   * Constructs a new <code>AsyncResponseHtmlAnalysisResponse</code>.
   * Asynchronous request
   * @alias module:model/AsyncResponseHtmlAnalysisResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AsyncResponseHtmlAnalysisResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AsyncResponseHtmlAnalysisResponse} obj Optional instance to populate.
   * @return {module:model/AsyncResponseHtmlAnalysisResponse} The populated <code>AsyncResponseHtmlAnalysisResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TaskId')) {
        obj['TaskId'] = ApiClient.convertToType(data['TaskId'], 'String');
      }
      if (data.hasOwnProperty('Result')) {
        obj['Result'] = HtmlAnalysisResponse.constructFromObject(data['Result']);
      }
    }
    return obj;
  }

  /**
   * Async task Id  <remarks>  Empty or null if task was processed synchronously  </remarks>
   * @member {String} TaskId
   */
  exports.prototype['TaskId'] = undefined;
  /**
   * Actual response
   * @member {module:model/HtmlAnalysisResponse} Result
   */
  exports.prototype['Result'] = undefined;



  return exports;
}));


