/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.ContextualThesaurusRequest = factory(root.ProWritingAidApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContextualThesaurusRequest model module.
   * @module model/ContextualThesaurusRequest
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>ContextualThesaurusRequest</code>.
   * @alias module:model/ContextualThesaurusRequest
   * @class
   * @param context {String} the word for the thesaurus call with surrounding context
   * @param contextStart {Number} the start position of the word to get suggestions for. 0 based
   * @param contextEnd {Number} the end position of the word to get suggestions for. 0 based. Would be the same as the start pos for a 1 letter word
   */
  var exports = function(context, contextStart, contextEnd) {
    var _this = this;

    _this['Context'] = context;
    _this['ContextStart'] = contextStart;
    _this['ContextEnd'] = contextEnd;
  };

  /**
   * Constructs a <code>ContextualThesaurusRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContextualThesaurusRequest} obj Optional instance to populate.
   * @return {module:model/ContextualThesaurusRequest} The populated <code>ContextualThesaurusRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Context')) {
        obj['Context'] = ApiClient.convertToType(data['Context'], 'String');
      }
      if (data.hasOwnProperty('ContextStart')) {
        obj['ContextStart'] = ApiClient.convertToType(data['ContextStart'], 'Number');
      }
      if (data.hasOwnProperty('ContextEnd')) {
        obj['ContextEnd'] = ApiClient.convertToType(data['ContextEnd'], 'Number');
      }
    }
    return obj;
  }

  /**
   * the word for the thesaurus call with surrounding context
   * @member {String} Context
   */
  exports.prototype['Context'] = undefined;
  /**
   * the start position of the word to get suggestions for. 0 based
   * @member {Number} ContextStart
   */
  exports.prototype['ContextStart'] = undefined;
  /**
   * the end position of the word to get suggestions for. 0 based. Would be the same as the start pos for a 1 letter word
   * @member {Number} ContextEnd
   * @default 8
   */
  exports.prototype['ContextEnd'] = 8;



  return exports;
}));


