/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.ContextualThesaurusResponse = factory(root.ProWritingAidApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContextualThesaurusResponse model module.
   * @module model/ContextualThesaurusResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>ContextualThesaurusResponse</code>.
   * @alias module:model/ContextualThesaurusResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ContextualThesaurusResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContextualThesaurusResponse} obj Optional instance to populate.
   * @return {module:model/ContextualThesaurusResponse} The populated <code>ContextualThesaurusResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Suggestions')) {
        obj['Suggestions'] = ApiClient.convertToType(data['Suggestions'], ['String']);
      }
    }
    return obj;
  }

  /**
   * List of context-specific suggestions
   * @member {Array.<String>} Suggestions
   */
  exports.prototype['Suggestions'] = undefined;



  return exports;
}));


