/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnalysisSummary', 'model/DocTag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AnalysisSummary'), require('./DocTag'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.TextAnalysisResponse = factory(root.ProWritingAidApiV2.ApiClient, root.ProWritingAidApiV2.AnalysisSummary, root.ProWritingAidApiV2.DocTag);
  }
}(this, function(ApiClient, AnalysisSummary, DocTag) {
  'use strict';




  /**
   * The TextAnalysisResponse model module.
   * @module model/TextAnalysisResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>TextAnalysisResponse</code>.
   * @alias module:model/TextAnalysisResponse
   * @class
   * @param tags {Array.<module:model/DocTag>} List of found suggestions
   * @param wordCount {Number} Number of processed words
   * @param summaries {Array.<module:model/AnalysisSummary>} 
   */
  var exports = function(tags, wordCount, summaries) {
    var _this = this;

    _this['Tags'] = tags;
    _this['WordCount'] = wordCount;
    _this['Summaries'] = summaries;
  };

  /**
   * Constructs a <code>TextAnalysisResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TextAnalysisResponse} obj Optional instance to populate.
   * @return {module:model/TextAnalysisResponse} The populated <code>TextAnalysisResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Tags')) {
        obj['Tags'] = ApiClient.convertToType(data['Tags'], [DocTag]);
      }
      if (data.hasOwnProperty('WordCount')) {
        obj['WordCount'] = ApiClient.convertToType(data['WordCount'], 'Number');
      }
      if (data.hasOwnProperty('Summaries')) {
        obj['Summaries'] = ApiClient.convertToType(data['Summaries'], [AnalysisSummary]);
      }
    }
    return obj;
  }

  /**
   * List of found suggestions
   * @member {Array.<module:model/DocTag>} Tags
   */
  exports.prototype['Tags'] = undefined;
  /**
   * Number of processed words
   * @member {Number} WordCount
   */
  exports.prototype['WordCount'] = undefined;
  /**
   * 
   * @member {Array.<module:model/AnalysisSummary>} Summaries
   */
  exports.prototype['Summaries'] = undefined;



  return exports;
}));


