/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.ThesaurusRequest = factory(root.ProWritingAidApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ThesaurusRequest model module.
   * @module model/ThesaurusRequest
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>ThesaurusRequest</code>.
   * @alias module:model/ThesaurusRequest
   * @class
   * @param word {String} the word for the thesaurus call
   * @param language {module:model/ThesaurusRequest.LanguageEnum} the language used
   */
  var exports = function(word, language) {
    var _this = this;

    _this['Word'] = word;
    _this['Language'] = language;
  };

  /**
   * Constructs a <code>ThesaurusRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ThesaurusRequest} obj Optional instance to populate.
   * @return {module:model/ThesaurusRequest} The populated <code>ThesaurusRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Word')) {
        obj['Word'] = ApiClient.convertToType(data['Word'], 'String');
      }
      if (data.hasOwnProperty('Language')) {
        obj['Language'] = ApiClient.convertToType(data['Language'], 'String');
      }
    }
    return obj;
  }

  /**
   * the word for the thesaurus call
   * @member {String} Word
   */
  exports.prototype['Word'] = undefined;
  /**
   * the language used
   * @member {module:model/ThesaurusRequest.LanguageEnum} Language
   * @default 'en'
   */
  exports.prototype['Language'] = 'en';


  /**
   * Allowed values for the <code>Language</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LanguageEnum = {
    /**
     * value: "en_US"
     * @const
     */
    "en_US": "en_US",
    /**
     * value: "en_UK"
     * @const
     */
    "en_UK": "en_UK",
    /**
     * value: "en"
     * @const
     */
    "en": "en",
    /**
     * value: "es"
     * @const
     */
    "es": "es"  };


  return exports;
}));


