/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntryMeaning'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntryMeaning'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.ThesaurusResponse = factory(root.ProWritingAidApiV2.ApiClient, root.ProWritingAidApiV2.EntryMeaning);
  }
}(this, function(ApiClient, EntryMeaning) {
  'use strict';




  /**
   * The ThesaurusResponse model module.
   * @module model/ThesaurusResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>ThesaurusResponse</code>.
   * @alias module:model/ThesaurusResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ThesaurusResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ThesaurusResponse} obj Optional instance to populate.
   * @return {module:model/ThesaurusResponse} The populated <code>ThesaurusResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Word')) {
        obj['Word'] = ApiClient.convertToType(data['Word'], 'String');
      }
      if (data.hasOwnProperty('Meanings')) {
        obj['Meanings'] = ApiClient.convertToType(data['Meanings'], [EntryMeaning]);
      }
    }
    return obj;
  }

  /**
   * The word that was searched
   * @member {String} Word
   */
  exports.prototype['Word'] = undefined;
  /**
   * List of context-specific meanings
   * @member {Array.<module:model/EntryMeaning>} Meanings
   */
  exports.prototype['Meanings'] = undefined;



  return exports;
}));


