/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.WordCloudResponse = factory(root.ProWritingAidApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WordCloudResponse model module.
   * @module model/WordCloudResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>WordCloudResponse</code>.
   * @alias module:model/WordCloudResponse
   * @class
   * @param url {String} the URL of the Word Cloud
   */
  var exports = function(url) {
    var _this = this;

    _this['Url'] = url;

  };

  /**
   * Constructs a <code>WordCloudResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WordCloudResponse} obj Optional instance to populate.
   * @return {module:model/WordCloudResponse} The populated <code>WordCloudResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Url')) {
        obj['Url'] = ApiClient.convertToType(data['Url'], 'String');
      }
      if (data.hasOwnProperty('Language')) {
        obj['Language'] = ApiClient.convertToType(data['Language'], 'String');
      }
    }
    return obj;
  }

  /**
   * the URL of the Word Cloud
   * @member {String} Url
   */
  exports.prototype['Url'] = undefined;
  /**
   * The detected language of the text
   * @member {String} Language
   */
  exports.prototype['Language'] = undefined;



  return exports;
}));


