/**
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ThesaurusRequest', 'model/ThesaurusResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ThesaurusRequest'), require('../model/ThesaurusResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ProWritingAidApiV2) {
      root.ProWritingAidApiV2 = {};
    }
    root.ProWritingAidApiV2.ThesaurusApi = factory(root.ProWritingAidApiV2.ApiClient, root.ProWritingAidApiV2.ThesaurusRequest, root.ProWritingAidApiV2.ThesaurusResponse);
  }
}(this, function(ApiClient, ThesaurusRequest, ThesaurusResponse) {
  'use strict';

  /**
   * Thesaurus service.
   * @module api/ThesaurusApi
   * @version 2.0.0
   */

  /**
   * Constructs a new ThesaurusApi. 
   * @alias module:api/ThesaurusApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Returns the thesaurus entries for a specific word
     * @param {module:model/ThesaurusRequest} request 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ThesaurusResponse} and HTTP response
     */
    this.postWithHttpInfo = function(request) {
      var postBody = request;

      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling post");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['licenseCode'];
      var contentTypes = ['application/json', 'text/json', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json'];
      var returnType = ThesaurusResponse;

      return this.apiClient.callApi(
        '/api/thesaurus', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Returns the thesaurus entries for a specific word
     * @param {module:model/ThesaurusRequest} request 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ThesaurusResponse}
     */
    this.post = function(request) {
      return this.postWithHttpInfo(request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
