/**
 * ProWritingAid API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnalysisSettings', 'model/AnalysisSummary', 'model/AnalysisSummaryGraph', 'model/AnalysisSummaryGraphItem', 'model/AnalysisSummaryItem', 'model/AnalysisSummarySubItem', 'model/AsyncResponseContextualThesaurusResponse', 'model/AsyncResponseHtmlAnalysisResponse', 'model/AsyncResponseSummaryAnalysisResponse', 'model/AsyncResponseTextAnalysisResponse', 'model/AsyncResponseWordCloudResponse', 'model/ContextualThesaurusRequest', 'model/ContextualThesaurusResponse', 'model/DocTag', 'model/HtmlAnalysisRequest', 'model/HtmlAnalysisResponse', 'model/SuggestionCategory', 'model/SummaryAnalysisRequest', 'model/SummaryAnalysisResponse', 'model/TextAnalysisRequest', 'model/TextAnalysisResponse', 'model/WordCloudRequest', 'model/WordCloudResponse', 'api/AsyncContextualThesaurusApi', 'api/AsyncContextualThesaurusResultApi', 'api/AsyncHtmlApi', 'api/AsyncHtmlResultApi', 'api/AsyncSummaryApi', 'api/AsyncSummaryResultApi', 'api/AsyncTextApi', 'api/AsyncTextResultApi', 'api/AsyncWordCloudApi', 'api/AsyncWordCloudResultApi', 'api/ContextualThesaurusApi', 'api/HtmlApi', 'api/SummaryApi', 'api/TextApi', 'api/WordCloudApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AnalysisSettings'), require('./model/AnalysisSummary'), require('./model/AnalysisSummaryGraph'), require('./model/AnalysisSummaryGraphItem'), require('./model/AnalysisSummaryItem'), require('./model/AnalysisSummarySubItem'), require('./model/AsyncResponseContextualThesaurusResponse'), require('./model/AsyncResponseHtmlAnalysisResponse'), require('./model/AsyncResponseSummaryAnalysisResponse'), require('./model/AsyncResponseTextAnalysisResponse'), require('./model/AsyncResponseWordCloudResponse'), require('./model/ContextualThesaurusRequest'), require('./model/ContextualThesaurusResponse'), require('./model/DocTag'), require('./model/HtmlAnalysisRequest'), require('./model/HtmlAnalysisResponse'), require('./model/SuggestionCategory'), require('./model/SummaryAnalysisRequest'), require('./model/SummaryAnalysisResponse'), require('./model/TextAnalysisRequest'), require('./model/TextAnalysisResponse'), require('./model/WordCloudRequest'), require('./model/WordCloudResponse'), require('./api/AsyncContextualThesaurusApi'), require('./api/AsyncContextualThesaurusResultApi'), require('./api/AsyncHtmlApi'), require('./api/AsyncHtmlResultApi'), require('./api/AsyncSummaryApi'), require('./api/AsyncSummaryResultApi'), require('./api/AsyncTextApi'), require('./api/AsyncTextResultApi'), require('./api/AsyncWordCloudApi'), require('./api/AsyncWordCloudResultApi'), require('./api/ContextualThesaurusApi'), require('./api/HtmlApi'), require('./api/SummaryApi'), require('./api/TextApi'), require('./api/WordCloudApi'));
  }
}(function(ApiClient, AnalysisSettings, AnalysisSummary, AnalysisSummaryGraph, AnalysisSummaryGraphItem, AnalysisSummaryItem, AnalysisSummarySubItem, AsyncResponseContextualThesaurusResponse, AsyncResponseHtmlAnalysisResponse, AsyncResponseSummaryAnalysisResponse, AsyncResponseTextAnalysisResponse, AsyncResponseWordCloudResponse, ContextualThesaurusRequest, ContextualThesaurusResponse, DocTag, HtmlAnalysisRequest, HtmlAnalysisResponse, SuggestionCategory, SummaryAnalysisRequest, SummaryAnalysisResponse, TextAnalysisRequest, TextAnalysisResponse, WordCloudRequest, WordCloudResponse, AsyncContextualThesaurusApi, AsyncContextualThesaurusResultApi, AsyncHtmlApi, AsyncHtmlResultApi, AsyncSummaryApi, AsyncSummaryResultApi, AsyncTextApi, AsyncTextResultApi, AsyncWordCloudApi, AsyncWordCloudResultApi, ContextualThesaurusApi, HtmlApi, SummaryApi, TextApi, WordCloudApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var ProWritingAidApi = require('index'); // See note below*.
   * var xxxSvc = new ProWritingAidApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new ProWritingAidApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new ProWritingAidApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new ProWritingAidApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AnalysisSettings model constructor.
     * @property {module:model/AnalysisSettings}
     */
    AnalysisSettings: AnalysisSettings,
    /**
     * The AnalysisSummary model constructor.
     * @property {module:model/AnalysisSummary}
     */
    AnalysisSummary: AnalysisSummary,
    /**
     * The AnalysisSummaryGraph model constructor.
     * @property {module:model/AnalysisSummaryGraph}
     */
    AnalysisSummaryGraph: AnalysisSummaryGraph,
    /**
     * The AnalysisSummaryGraphItem model constructor.
     * @property {module:model/AnalysisSummaryGraphItem}
     */
    AnalysisSummaryGraphItem: AnalysisSummaryGraphItem,
    /**
     * The AnalysisSummaryItem model constructor.
     * @property {module:model/AnalysisSummaryItem}
     */
    AnalysisSummaryItem: AnalysisSummaryItem,
    /**
     * The AnalysisSummarySubItem model constructor.
     * @property {module:model/AnalysisSummarySubItem}
     */
    AnalysisSummarySubItem: AnalysisSummarySubItem,
    /**
     * The AsyncResponseContextualThesaurusResponse model constructor.
     * @property {module:model/AsyncResponseContextualThesaurusResponse}
     */
    AsyncResponseContextualThesaurusResponse: AsyncResponseContextualThesaurusResponse,
    /**
     * The AsyncResponseHtmlAnalysisResponse model constructor.
     * @property {module:model/AsyncResponseHtmlAnalysisResponse}
     */
    AsyncResponseHtmlAnalysisResponse: AsyncResponseHtmlAnalysisResponse,
    /**
     * The AsyncResponseSummaryAnalysisResponse model constructor.
     * @property {module:model/AsyncResponseSummaryAnalysisResponse}
     */
    AsyncResponseSummaryAnalysisResponse: AsyncResponseSummaryAnalysisResponse,
    /**
     * The AsyncResponseTextAnalysisResponse model constructor.
     * @property {module:model/AsyncResponseTextAnalysisResponse}
     */
    AsyncResponseTextAnalysisResponse: AsyncResponseTextAnalysisResponse,
    /**
     * The AsyncResponseWordCloudResponse model constructor.
     * @property {module:model/AsyncResponseWordCloudResponse}
     */
    AsyncResponseWordCloudResponse: AsyncResponseWordCloudResponse,
    /**
     * The ContextualThesaurusRequest model constructor.
     * @property {module:model/ContextualThesaurusRequest}
     */
    ContextualThesaurusRequest: ContextualThesaurusRequest,
    /**
     * The ContextualThesaurusResponse model constructor.
     * @property {module:model/ContextualThesaurusResponse}
     */
    ContextualThesaurusResponse: ContextualThesaurusResponse,
    /**
     * The DocTag model constructor.
     * @property {module:model/DocTag}
     */
    DocTag: DocTag,
    /**
     * The HtmlAnalysisRequest model constructor.
     * @property {module:model/HtmlAnalysisRequest}
     */
    HtmlAnalysisRequest: HtmlAnalysisRequest,
    /**
     * The HtmlAnalysisResponse model constructor.
     * @property {module:model/HtmlAnalysisResponse}
     */
    HtmlAnalysisResponse: HtmlAnalysisResponse,
    /**
     * The SuggestionCategory model constructor.
     * @property {module:model/SuggestionCategory}
     */
    SuggestionCategory: SuggestionCategory,
    /**
     * The SummaryAnalysisRequest model constructor.
     * @property {module:model/SummaryAnalysisRequest}
     */
    SummaryAnalysisRequest: SummaryAnalysisRequest,
    /**
     * The SummaryAnalysisResponse model constructor.
     * @property {module:model/SummaryAnalysisResponse}
     */
    SummaryAnalysisResponse: SummaryAnalysisResponse,
    /**
     * The TextAnalysisRequest model constructor.
     * @property {module:model/TextAnalysisRequest}
     */
    TextAnalysisRequest: TextAnalysisRequest,
    /**
     * The TextAnalysisResponse model constructor.
     * @property {module:model/TextAnalysisResponse}
     */
    TextAnalysisResponse: TextAnalysisResponse,
    /**
     * The WordCloudRequest model constructor.
     * @property {module:model/WordCloudRequest}
     */
    WordCloudRequest: WordCloudRequest,
    /**
     * The WordCloudResponse model constructor.
     * @property {module:model/WordCloudResponse}
     */
    WordCloudResponse: WordCloudResponse,
    /**
     * The AsyncContextualThesaurusApi service constructor.
     * @property {module:api/AsyncContextualThesaurusApi}
     */
    AsyncContextualThesaurusApi: AsyncContextualThesaurusApi,
    /**
     * The AsyncContextualThesaurusResultApi service constructor.
     * @property {module:api/AsyncContextualThesaurusResultApi}
     */
    AsyncContextualThesaurusResultApi: AsyncContextualThesaurusResultApi,
    /**
     * The AsyncHtmlApi service constructor.
     * @property {module:api/AsyncHtmlApi}
     */
    AsyncHtmlApi: AsyncHtmlApi,
    /**
     * The AsyncHtmlResultApi service constructor.
     * @property {module:api/AsyncHtmlResultApi}
     */
    AsyncHtmlResultApi: AsyncHtmlResultApi,
    /**
     * The AsyncSummaryApi service constructor.
     * @property {module:api/AsyncSummaryApi}
     */
    AsyncSummaryApi: AsyncSummaryApi,
    /**
     * The AsyncSummaryResultApi service constructor.
     * @property {module:api/AsyncSummaryResultApi}
     */
    AsyncSummaryResultApi: AsyncSummaryResultApi,
    /**
     * The AsyncTextApi service constructor.
     * @property {module:api/AsyncTextApi}
     */
    AsyncTextApi: AsyncTextApi,
    /**
     * The AsyncTextResultApi service constructor.
     * @property {module:api/AsyncTextResultApi}
     */
    AsyncTextResultApi: AsyncTextResultApi,
    /**
     * The AsyncWordCloudApi service constructor.
     * @property {module:api/AsyncWordCloudApi}
     */
    AsyncWordCloudApi: AsyncWordCloudApi,
    /**
     * The AsyncWordCloudResultApi service constructor.
     * @property {module:api/AsyncWordCloudResultApi}
     */
    AsyncWordCloudResultApi: AsyncWordCloudResultApi,
    /**
     * The ContextualThesaurusApi service constructor.
     * @property {module:api/ContextualThesaurusApi}
     */
    ContextualThesaurusApi: ContextualThesaurusApi,
    /**
     * The HtmlApi service constructor.
     * @property {module:api/HtmlApi}
     */
    HtmlApi: HtmlApi,
    /**
     * The SummaryApi service constructor.
     * @property {module:api/SummaryApi}
     */
    SummaryApi: SummaryApi,
    /**
     * The TextApi service constructor.
     * @property {module:api/TextApi}
     */
    TextApi: TextApi,
    /**
     * The WordCloudApi service constructor.
     * @property {module:api/WordCloudApi}
     */
    WordCloudApi: WordCloudApi,
    /**
     * Common tests-only license code
     */
    TestLicenseCode: "00000000-0000-0000-0000-2212FC205139"
  };

  return exports;
}));
